all: fumadores productor-consumidor

fumadores:fumadores.cpp
	g++ -o fumadores fumadores.cpp -lpthread

productor-consumidor: productor-consumidor.cpp
	g++ -o productor-consumidor productor-consumidor.cpp -lpthread
